FROM alpine AS builder

ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1
FROM arm32v7/python:3.7-slim
ARG usebranche="dev"
ENV pullbranche=${usebranche}
COPY --from=builder qemu-arm-static /usr/bin  
# 增加适配玩客云arm7 32位环境 chrome默认安装 90版本
RUN apt-get update
RUN apt-get install -y wget unzip libzbar0 git cron 
RUN apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev python3-pip
RUN apt-get install libjpeg-dev zlib1g-dev 
RUN cd /xuexi/; wget https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/pool/universe/c/chromium-browser/chromium-chromedriver_90.0.4430.72-0ubuntu0.16.04.1_armhf.deb; dpkg -i chromium-chromedriver_90.0.4430.72-0ubuntu0.16.04.1_armhf.deb; apt-get -fy install; google-chrome --version; rm -f chromium-chromedriver_90.0.4430.72-0ubuntu0.16.04.1_armhf.deb
#RUN cd /xuexi/; wget -O chromedriver_linux64_92.0.4515.107.zip http://npm.taobao.org/mirrors/chromedriver/92.0.4515.107/chromedriver_linux64.zip; unzip chromedriver_linux64_92.0.4515.107.zip; chmod 755 chromedriver; ls -la; ./chromedriver --version
ENV TZ=Asia/Shanghai
ENV AccessToken=
ENV Secret=
ENV Nohead=True
ENV Pushmode=1
ENV islooplogin=False
ENV Sourcepath="https://github.com.cnpmjs.org/TechXueXi/TechXueXi.git"
ENV CRONTIME="30 9 * * *"
# RUN rm -f /xuexi/config/*; ls -la
COPY requirements.txt /xuexi/requirements.txt
COPY run.sh /xuexi/run.sh 
COPY start.sh /xuexi/start.sh 
RUN pip install -r /xuexi/requirements.txt
WORKDIR /xuexi
RUN chmod +x ./run.sh
RUN chmod +x ./start.sh
RUN mkdir code
WORKDIR /xuexi/code
RUN git clone -b ${pullbranche} ${Sourcepath}
WORKDIR /xuexi
ENTRYPOINT ["/bin/bash", "./start.sh"]
