FROM ubuntu AS builder
RUN apt-get update
RUN apt-get install qemu
#ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v6.0.0%2Bbalena1/qemu-6.0.0.balena1-arm.tar.gz
#RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1
FROM arm32v7/python:3.7-slim
ARG usebranche="dev"
ENV pullbranche=${usebranche}
COPY --from=builder qemu-arm-static /usr/bin  
# 增加适配玩客云arm7 32位环境 chrome默认安装 90版本
#COPY ./sources.list .
#RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && mv ./sources.list /etc/apt/
#RUN apt-get update
#RUN apt-get autoremove dpkg
#RUN apt-get install dpkg 
#RUN mv /etc/lib/dpkg/info /etc/lib/dpkg/info-old
#RUN mkdir /etc/lib/dpkg/info
#RUN apt-get clean
#RUN apt-get install -f
#RUN dpkg --configure -a

#RUN apt-get --reinstall install `dpkg --get-selections | grep '[[:space:]]install' | cut -f1`#RUN rm /var/lib/dpkg/updates/*

RUN apt-get upgrade
RUN apt-get install -y wget unzip libzbar0 git cron chromium-driver; chromedriver --version; which chromedriver; chromium --version
RUN apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev python3-pip
RUN apt-get install libjpeg-dev zlib1g-dev 
ENV TZ=Asia/Shanghai
ENV AccessToken=
ENV Secret=
ENV Nohead=True
ENV Pushmode=1
ENV islooplogin=False
ENV Sourcepath="https://github.com.cnpmjs.org/TechXueXi/TechXueXi.git"
ENV CRONTIME="30 9 * * *"
# RUN rm -f /xuexi/config/*; ls -la
COPY requirements.txt /xuexi/requirements.txt
COPY run.sh /xuexi/run.sh 
COPY start.sh /xuexi/start.sh 
RUN pip install -r /xuexi/requirements.txt
#RUN cd /xuexi/; wget http://launchpadlibrarian.net/361669488/chromium-chromedriver_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb; dpkg -i chromium-chromedriver_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb; apt-get -fy install;  rm -f chromium-chromedriver_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb; chromedriver --version; chromium --version
#RUN cd /xuexi/; wget -O chromedriver_linux64_92.0.4515.107.zip http://npm.taobao.org/mirrors/chromedriver/92.0.4515.107/chromedriver_linux64.zip; unzip chromedriver_linux64_92.0.4515.107.zip; chmod 755 chromedriver; ls -la; ./chromedriver --version
WORKDIR /xuexi
RUN chmod +x ./run.sh
RUN chmod +x ./start.sh
RUN mkdir code
WORKDIR /xuexi/code
RUN git clone -b ${pullbranche} ${Sourcepath}
WORKDIR /xuexi
ENTRYPOINT ["/bin/bash", "./start.sh"]
